<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // Add One Items (Category ID: 22)
            [
                'category_id' => 22,
                'name' => 'Add Banana',
                'image' => 'images/items/add_banana.jpg',
                'description' => 'Add Banana',
                'price' => 50000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Add Brownie Cake',
                'image' => 'images/items/add_brownie_cake.jpg',
                'description' => 'Add Brownie Cake',
                'price' => 50000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Add Ice Cream Ball',
                'image' => 'images/items/add_ice_cream_ball.jpg',
                'description' => 'Add Ice Cream Ball',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Add Lotus Biscuits',
                'image' => 'images/items/add_lotus_biscuits.jpg',
                'description' => 'Add Lotus Biscuits',
                'price' => 50000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Add Oreo Biscuits',
                'image' => 'images/items/add_oreo_biscuits.jpg',
                'description' => 'Add Oreo Biscuits',
                'price' => 50000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Add Peach',
                'image' => 'images/items/add_peach.jpg',
                'description' => 'Add Peach',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Add Pistachio Topping',
                'image' => 'images/items/add_pistachio_topping.jpg',
                'description' => 'Add Pistachio Topping',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Add Spread Topping',
                'image' => 'images/items/add_spread_topping.jpg',
                'description' => 'Add Spread Topping',
                'price' => 50000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Add Strawberry',
                'image' => 'images/items/add_strawberry.jpg',
                'description' => 'Add Strawberry',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Any Spread Shot',
                'image' => 'images/items/any_spread_shot.jpg',
                'description' => 'Any Spread Shot',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Belgium Chocolate Shot',
                'image' => 'images/items/belgium_chocolate_shot.jpg',
                'description' => 'Belgium Chocolate Shot',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 22,
                'name' => 'Pistachio Shot',
                'image' => 'images/items/pistachio_shot.jpg',
                'description' => 'Pistachio Shot',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Intab Cake Items (Category ID: 15)
            [
                'category_id' => 15,
                'name' => 'Intab Pistachio',
                'image' => 'images/items/intab_pistachio.jpg',
                'description' => 'Intab Pistachio',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 15,
                'name' => 'Intab Belgium',
                'image' => 'images/items/intab_belgium.jpg',
                'description' => 'Intab Belgium',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Bubble Waffle Items (Category ID: 3)
            [
                'category_id' => 3,
                'name' => 'Add Ball Ice Cream',
                'image' => 'images/items/add_ball_ice_cream_bubble.jpg',
                'description' => 'Add Ball Ice Cream',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Add Fruits',
                'image' => 'images/items/add_fruits_bubble.jpg',
                'description' => 'Add Fruits',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Belgium Bubble Waffle',
                'image' => 'images/items/belgium_bubble_waffle.jpg',
                'description' => 'Belgium Bubble Waffle',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Dark Bubble Waffle',
                'image' => 'images/items/dark_bubble_waffle.jpg',
                'description' => 'Dark Bubble Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Galaxy Bubble Waffle',
                'image' => 'images/items/galaxy_bubble_waffle.jpg',
                'description' => 'Galaxy Bubble Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Ice Cream Ball Bubble Waffle',
                'image' => 'images/items/ice_cream_ball_bubble_waffle.jpg',
                'description' => 'Ice Cream Ball Bubble Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Italian Bubble Waffle',
                'image' => 'images/items/italian_bubble_waffle.jpg',
                'description' => 'Italian Bubble Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Lotus Bubble Waffle',
                'image' => 'images/items/lotus_bubble_waffle.jpg',
                'description' => 'Lotus Bubble Waffle',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Merry Cream Bubble Waffle',
                'image' => 'images/items/merry_cream_bubble_waffle.jpg',
                'description' => 'Merry Cream Bubble Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Mix Flavors Bubble Waffle',
                'image' => 'images/items/mix_flavors_bubble_waffle.jpg',
                'description' => 'Mix Flavors Bubble Waffle',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Nutella Bubble Waffle',
                'image' => 'images/items/nutella_bubble_waffle.jpg',
                'description' => 'Nutella Bubble Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Oreo Bubble Waffle',
                'image' => 'images/items/oreo_bubble_waffle.jpg',
                'description' => 'Oreo Bubble Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'Pistachio Bubble Waffle',
                'image' => 'images/items/pistachio_bubble_waffle.jpg',
                'description' => 'Pistachio Bubble Waffle',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 3,
                'name' => 'White Bubble Waffle',
                'image' => 'images/items/white_bubble_waffle.jpg',
                'description' => 'White Bubble Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Circle Waffle Items (Category ID: 4)
            [
                'category_id' => 4,
                'name' => 'Italian Circle Waffle',
                'image' => 'images/items/italian_circle_waffle.jpg',
                'description' => 'Italian Circle Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Add Ball Ice Cream',
                'image' => 'images/items/add_ball_ice_cream_circle.jpg',
                'description' => 'Add Ball Ice Cream',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Add Fruits',
                'image' => 'images/items/add_fruits_circle.jpg',
                'description' => 'Add Fruits',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Belgium Circle Waffle',
                'image' => 'images/items/belgium_circle_waffle.jpg',
                'description' => 'Belgium Circle Waffle',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Dark Circle Waffle',
                'image' => 'images/items/dark_circle_waffle.jpg',
                'description' => 'Dark Circle Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Galaxy Circle Waffle',
                'image' => 'images/items/galaxy_circle_waffle.jpg',
                'description' => 'Galaxy Circle Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Lotus Circle Waffle',
                'image' => 'images/items/lotus_circle_waffle.jpg',
                'description' => 'Lotus Circle Waffle',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Mix Flavors Circle Waffle',
                'image' => 'images/items/mix_flavors_circle_waffle.jpg',
                'description' => 'Mix Flavors Circle Waffle',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Nutella Circle Waffle',
                'image' => 'images/items/nutella_circle_waffle.jpg',
                'description' => 'Nutella Circle Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Oreo Circle Waffle',
                'image' => 'images/items/oreo_circle_waffle.jpg',
                'description' => 'Oreo Circle Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'Pistachio Circle Waffle',
                'image' => 'images/items/pistachio_circle_waffle.jpg',
                'description' => 'Pistachio Circle Waffle',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 4,
                'name' => 'White Circle Waffle',
                'image' => 'images/items/white_circle_waffle.jpg',
                'description' => 'White Circle Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Crepe Items (Category ID: 1)
            [
                'category_id' => 1,
                'name' => 'Nutella Crepe',
                'image' => 'images/items/nutella_crepe.jpg',
                'description' => 'Nutella Crepe',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Oreo Crepe',
                'image' => 'images/items/oreo_crepe.jpg',
                'description' => 'Oreo Crepe',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Dubai Triangle Crepe',
                'image' => 'images/items/dubai_triangle_crepe.jpg',
                'description' => 'Dubai Triangle Crepe',
                'price' => 600000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Lotus Crepe',
                'image' => 'images/items/lotus_crepe.jpg',
                'description' => 'Lotus Crepe',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Pistachio Lotus Crepe with Strawberry',
                'image' => 'images/items/pistachio_lotus_crepe_with_strawberry.jpg',
                'description' => 'Pistachio Lotus Crepe with Strawberry',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Triangle Crepe With Fruits',
                'image' => 'images/items/triangle_crepe_with_fruits.jpg',
                'description' => 'Triangle Crepe With Fruits',
                'price' => 600000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Triangle Italian Crepe',
                'image' => 'images/items/triangle_italian_crepe.jpg',
                'description' => 'Triangle Italian Crepe',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'White Crepe',
                'image' => 'images/items/white_crepe.jpg',
                'description' => 'White Crepe',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Kinder Crepe',
                'image' => 'images/items/kinder_crepe.jpg',
                'description' => 'Kinder Crepe',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Belgium Crepe',
                'image' => 'images/items/belgium_crepe.jpg',
                'description' => 'Belgium Crepe',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Brownie Crepe',
                'image' => 'images/items/brownie_crepe.jpg',
                'description' => 'Brownie Crepe',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Crepe With Strawberry',
                'image' => 'images/items/crepe_with_strawberry.jpg',
                'description' => 'Crepe With Strawberry',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Dark Crepe',
                'image' => 'images/items/dark_crepe.jpg',
                'description' => 'Dark Crepe',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Dubai Roll Crepe With Fruits',
                'image' => 'images/items/dubai_roll_crepe_with_fruits.jpg',
                'description' => 'Dubai Roll Crepe With Fruits',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Dubai Roll Crepe With Ice Cream',
                'image' => 'images/items/dubai_roll_crepe_with_ice_cream.jpg',
                'description' => 'Dubai Roll Crepe With Ice Cream',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Dubai Square Crepe',
                'image' => 'images/items/dubai_square_crepe.jpg',
                'description' => 'Dubai Square Crepe',
                'price' => 600000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Galaxy Crepe',
                'image' => 'images/items/galaxy_crepe.jpg',
                'description' => 'Galaxy Crepe',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Italian Crepe',
                'image' => 'images/items/italian_crepe.jpg',
                'description' => 'Italian Crepe',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Mix Flavors Crepe',
                'image' => 'images/items/mix_flavors_crepe.jpg',
                'description' => 'Mix Flavors Crepe',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Osmalya Crepe with Belgium',
                'image' => 'images/items/osmalya_crepe_with_belgium.jpg',
                'description' => 'Osmalya Crepe with Belgium',
                'price' => 1000000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Pistachio Crepe',
                'image' => 'images/items/pistachio_crepe.jpg',
                'description' => 'Pistachio Crepe',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Red Valvet Crepe',
                'image' => 'images/items/red_valvet_crepe.jpg',
                'description' => 'Red Valvet Crepe',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 1,
                'name' => 'Add Fruits',
                'image' => 'images/items/add_fruits_crepe.jpg',
                'description' => 'Add Fruits',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Cups Items (Category ID: 11)
            [
                'category_id' => 11,
                'name' => 'Belgium Cup',
                'image' => 'images/items/belgium_cup.jpg',
                'description' => 'Belgium Cup',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 11,
                'name' => 'Brownie Cup',
                'image' => 'images/items/brownie_cup.jpg',
                'description' => 'Brownie Cup',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 11,
                'name' => 'Crispy Rice Belgium Cup',
                'image' => 'images/items/crispy_rice_belgium_cup.jpg',
                'description' => 'Crispy Rice Belgium Cup',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 11,
                'name' => 'Dubai Cup',
                'image' => 'images/items/dubai_cup.jpg',
                'description' => 'Dubai Cup',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 11,
                'name' => 'Red Velvet Cup',
                'image' => 'images/items/red_velvet_cup.jpg',
                'description' => 'Red Velvet Cup',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 11,
                'name' => 'Strawberry Cup',
                'image' => 'images/items/strawberry_cup.jpg',
                'description' => 'Strawberry Cup',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Desserts Items (Category ID: 14)
            [
                'category_id' => 14,
                'name' => 'Blueberry Tart',
                'image' => 'images/items/blueberry_tart.jpg',
                'description' => 'Blueberry Tart',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Mango Tart',
                'image' => 'images/items/mango_tart.jpg',
                'description' => 'Mango Tart',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'oriental Tart',
                'image' => 'images/items/oriental_tart.jpg',
                'description' => 'oriental Tart',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Eclair Caramel',
                'image' => 'images/items/eclair_caramel.jpg',
                'description' => 'Eclair Caramel',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Eclair Chocolate',
                'image' => 'images/items/eclair_chocolate.jpg',
                'description' => 'Eclair Chocolate',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Eclair Lotus',
                'image' => 'images/items/eclair_lotus.jpg',
                'description' => 'Eclair Lotus',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Eclair Strawberry',
                'image' => 'images/items/eclair_strawberry.jpg',
                'description' => 'Eclair Strawberry',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Lotus Can Cake',
                'image' => 'images/items/lotus_can_cake.jpg',
                'description' => 'Lotus Can Cake',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Millefeuille',
                'image' => 'images/items/millefeuille.jpg',
                'description' => 'Millefeuille',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Millefeuille Raspberry Cup',
                'image' => 'images/items/millefeuille_raspberry_cup.jpg',
                'description' => 'Millefeuille Raspberry Cup',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Muffins',
                'image' => 'images/items/muffins.jpg',
                'description' => 'Muffins',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Blueberry Can Cake',
                'image' => 'images/items/blueberry_can_cake.jpg',
                'description' => 'Blueberry Can Cake',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Paris Breast',
                'image' => 'images/items/paris_breast.jpg',
                'description' => 'Paris Breast',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Pistachio Can Cake',
                'image' => 'images/items/pistachio_can_cake.jpg',
                'description' => 'Pistachio Can Cake',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Profiterole Creamy',
                'image' => 'images/items/profiterole_creamy.jpg',
                'description' => 'Profiterole Creamy',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Red Velvet Piece',
                'image' => 'images/items/red_velvet_piece.jpg',
                'description' => 'Red Velvet Piece',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Strawberry Can Cake',
                'image' => 'images/items/strawberry_can_cake.jpg',
                'description' => 'Strawberry Can Cake',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Strawberry Tart',
                'image' => 'images/items/strawberry_tart.jpg',
                'description' => 'Strawberry Tart',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 14,
                'name' => 'Tropezian',
                'image' => 'images/items/tropezian.jpg',
                'description' => 'Tropezian',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Donuts Waffle Items (Category ID: 5)
            [
                'category_id' => 5,
                'name' => 'Add Fruits',
                'image' => 'images/items/add_fruits_donuts.jpg',
                'description' => 'Add Fruits',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Add Ice Cream Ball',
                'image' => 'images/items/add_ice_cream_ball_donuts.jpg',
                'description' => 'Add Ice Cream Ball',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Belgium Chocolate donuts Waffle',
                'image' => 'images/items/belgium_chocolate_donuts_waffle.jpg',
                'description' => 'Belgium Chocolate donuts Waffle',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Dark donuts Waffle',
                'image' => 'images/items/dark_donuts_waffle.jpg',
                'description' => 'Dark donuts Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Galaxy donuts Waffle',
                'image' => 'images/items/galaxy_donuts_waffle.jpg',
                'description' => 'Galaxy donuts Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Italian donuts waffle',
                'image' => 'images/items/italian_donuts_waffle.jpg',
                'description' => 'Italian donuts waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Lotus donuts Waffle',
                'image' => 'images/items/lotus_donuts_waffle.jpg',
                'description' => 'Lotus donuts Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Mix Flavors donuts Waffle',
                'image' => 'images/items/mix_flavors_donuts_waffle.jpg',
                'description' => 'Mix Flavors donuts Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Nutella donuts Waffle',
                'image' => 'images/items/nutella_donuts_waffle.jpg',
                'description' => 'Nutella donuts Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Oreo donuts',
                'image' => 'images/items/oreo_donuts.jpg',
                'description' => 'Oreo donuts',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'Pistachio donuts Waffle',
                'image' => 'images/items/pistachio_donuts_waffle.jpg',
                'description' => 'Pistachio donuts Waffle',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 5,
                'name' => 'White donuts Waffle',
                'image' => 'images/items/white_donuts_waffle.jpg',
                'description' => 'White donuts Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Fettuccine Items (Category ID: 18)
            [
                'category_id' => 18,
                'name' => 'Add Fruits',
                'image' => 'images/items/add_fruits_fettuccine.jpg',
                'description' => 'Add Fruits',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Add Ice Cream Ball',
                'image' => 'images/items/add_ice_cream_ball_fettuccine.jpg',
                'description' => 'Add Ice Cream Ball',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Belgium Fettuccine',
                'image' => 'images/items/belgium_fettuccine.jpg',
                'description' => 'Belgium Fettuccine',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Dark Fettuccine',
                'image' => 'images/items/dark_fettuccine.jpg',
                'description' => 'Dark Fettuccine',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Galaxy Fettuccine',
                'image' => 'images/items/galaxy_fettuccine.jpg',
                'description' => 'Galaxy Fettuccine',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Italian Fettuccine',
                'image' => 'images/items/italian_fettuccine.jpg',
                'description' => 'Italian Fettuccine',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Kinder Fettuccine',
                'image' => 'images/items/kinder_fettuccine.jpg',
                'description' => 'Kinder Fettuccine',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Lotus Fettuccine',
                'image' => 'images/items/lotus_fettuccine.jpg',
                'description' => 'Lotus Fettuccine',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Nutella Fettuccine',
                'image' => 'images/items/nutella_fettuccine.jpg',
                'description' => 'Nutella Fettuccine',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Oreo Fettuccine',
                'image' => 'images/items/oreo_fettuccine.jpg',
                'description' => 'Oreo Fettuccine',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'triple chocolate fettuccine with ice cream ball',
                'image' => 'images/items/triple_chocolate_fettuccine_with_ice_cream_ball.jpg',
                'description' => 'triple chocolate fettuccine with ice cream ball',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'Pistachio Fettuccine',
                'image' => 'images/items/pistachio_fettuccine.jpg',
                'description' => 'Pistachio Fettuccine',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 18,
                'name' => 'White Fettuccine',
                'image' => 'images/items/white_fettuccine.jpg',
                'description' => 'White Fettuccine',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Gym Items (Category ID: 20)
            [
                'category_id' => 20,
                'name' => 'Add Diet Ice Cream Vanilla',
                'image' => 'images/items/add_diet_ice_cream_vanilla.jpg',
                'description' => 'Add Diet Ice Cream Vanilla',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 20,
                'name' => 'Add Fruits',
                'image' => 'images/items/add_fruits_gym.jpg',
                'description' => 'Add Fruits',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 20,
                'name' => 'Add Honey Spoon',
                'image' => 'images/items/add_honey_spoon.jpg',
                'description' => 'Add Honey Spoon',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 20,
                'name' => 'Protien Small Pancake',
                'image' => 'images/items/protien_small_pancake.jpg',
                'description' => 'Protien Small Pancake',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Merry Cream Cone Items (Category ID: 12)
            [
                'category_id' => 12,
                'name' => 'Coated Cone',
                'image' => 'images/items/coated_cone.jpg',
                'description' => 'Coated Cone',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 12,
                'name' => 'Dipped Large Cone',
                'image' => 'images/items/dipped_large_cone.jpg',
                'description' => 'Dipped Large Cone',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 12,
                'name' => 'Large Cone',
                'image' => 'images/items/large_cone.jpg',
                'description' => 'Large Cone',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 12,
                'name' => 'Medium Cone',
                'image' => 'images/items/medium_cone.jpg',
                'description' => 'Medium Cone',
                'price' => 150000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 12,
                'name' => 'Small Cone',
                'image' => 'images/items/small_cone.jpg',
                'description' => 'Small Cone',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 12,
                'name' => 'Sugar Cone',
                'image' => 'images/items/sugar_cone.jpg',
                'description' => 'Sugar Cone',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Merry Cream Cup Items (Category ID: 13)
            [
                'category_id' => 13,
                'name' => 'Large Cup',
                'image' => 'images/items/large_cup.jpg',
                'description' => 'Large Cup',
                'price' => 250000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 13,
                'name' => 'Large Cup Open Toppings',
                'image' => 'images/items/large_cup_open_toppings.jpg',
                'description' => 'Large Cup Open Toppings',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 13,
                'name' => 'Small Cup',
                'image' => 'images/items/small_cup.jpg',
                'description' => 'Small Cup',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 13,
                'name' => 'Small Cup Open Toppings',
                'image' => 'images/items/small_cup_open_toppings.jpg',
                'description' => 'Small Cup Open Toppings',
                'price' => 300000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 13,
                'name' => 'Add Pistachio or Chocolate',
                'image' => 'images/items/add_pistachio_or_chocolate.jpg',
                'description' => 'Add Pistachio or Chocolate',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Mighty Crepe Items (Category ID: 2)
            [
                'category_id' => 2,
                'name' => 'Mighty Mix Brownie',
                'image' => 'images/items/mighty_mix_brownie.jpg',
                'description' => 'Mighty Mix Brownie',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'Mighty Mix Brownie Belgium',
                'image' => 'images/items/mighty_mix_brownie_belgium.jpg',
                'description' => 'Mighty Mix Brownie Belgium',
                'price' => 750000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'Mighty Mix Red Valvet',
                'image' => 'images/items/mighty_mix_red_valvet.jpg',
                'description' => 'Mighty Mix Red Valvet',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 2,
                'name' => 'Mighty Mix Red Valvet Belgium',
                'image' => 'images/items/mighty_mix_red_valvet_belgium.jpg',
                'description' => 'Mighty Mix Red Valvet Belgium',
                'price' => 750000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Mini Pancake Balls Items (Category ID: 8)
            [
                'category_id' => 8,
                'name' => '10 Balls With Fruits',
                'image' => 'images/items/10_balls_with_fruits.jpg',
                'description' => '10 Balls With Fruits',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => '16 Mini Pancake Balls Mix Flavors',
                'image' => 'images/items/16_mini_pancake_balls_mix_flavors.jpg',
                'description' => '16 Mini Pancake Balls Mix Flavors',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => '16 Mini Pancake Balls white or choco',
                'image' => 'images/items/16_mini_pancake_balls_white_or_choco.jpg',
                'description' => '16 Mini Pancake Balls white or choco',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'Belgium mini Pancake Balls',
                'image' => 'images/items/belgium_mini_pancake_balls.jpg',
                'description' => 'Belgium mini Pancake Balls',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'Dark Mini 10 Pancake Balls',
                'image' => 'images/items/dark_mini_10_pancake_balls.jpg',
                'description' => 'Dark Mini 10 Pancake Balls',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'Galaxy Mini Pancake Balls',
                'image' => 'images/items/galaxy_mini_pancake_balls.jpg',
                'description' => 'Galaxy Mini Pancake Balls',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'Italian mini Pancake Balls',
                'image' => 'images/items/italian_mini_pancake_balls.jpg',
                'description' => 'Italian mini Pancake Balls',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'Kinder Mini Pancake Balls',
                'image' => 'images/items/kinder_mini_pancake_balls.jpg',
                'description' => 'Kinder Mini Pancake Balls',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'Lotus mini Pancake Balls',
                'image' => 'images/items/lotus_mini_pancake_balls.jpg',
                'description' => 'Lotus mini Pancake Balls',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'Nutella mini Pancake Balls',
                'image' => 'images/items/nutella_mini_pancake_balls.jpg',
                'description' => 'Nutella mini Pancake Balls',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'Oreo mini Pancake Balls',
                'image' => 'images/items/oreo_mini_pancake_balls.jpg',
                'description' => 'Oreo mini Pancake Balls',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'Pistachio Mini Pancake Balls',
                'image' => 'images/items/pistachio_mini_pancake_balls.jpg',
                'description' => 'Pistachio Mini Pancake Balls',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 8,
                'name' => 'White Mini 10 Pancake Balls',
                'image' => 'images/items/white_mini_10_pancake_balls.jpg',
                'description' => 'White Mini 10 Pancake Balls',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Mou Items (Category ID: 16)
            [
                'category_id' => 16,
                'name' => 'Chocolate Mou',
                'image' => 'images/items/chocolate_mou.jpg',
                'description' => 'Chocolate Mou',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 16,
                'name' => 'Mix berries Mou',
                'image' => 'images/items/mix_berries_mou.jpg',
                'description' => 'Mix berries Mou',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 16,
                'name' => 'Pistachio Mou',
                'image' => 'images/items/pistachio_mou.jpg',
                'description' => 'Pistachio Mou',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 16,
                'name' => 'Strawberry Mou',
                'image' => 'images/items/strawberry_mou.jpg',
                'description' => 'Strawberry Mou',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Pancake Items (Category ID: 9)
            [
                'category_id' => 9,
                'name' => 'Belgium Pancake',
                'image' => 'images/items/belgium_pancake.jpg',
                'description' => 'Belgium Pancake',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Brownie Pancake',
                'image' => 'images/items/brownie_pancake.jpg',
                'description' => 'Brownie Pancake',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Dark Pancake',
                'image' => 'images/items/dark_pancake.jpg',
                'description' => 'Dark Pancake',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Add Fruits',
                'image' => 'images/items/add_fruits_pancake.jpg',
                'description' => 'Add Fruits',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Galaxy Pancake',
                'image' => 'images/items/galaxy_pancake.jpg',
                'description' => 'Galaxy Pancake',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Italian Pancake',
                'image' => 'images/items/italian_pancake.jpg',
                'description' => 'Italian Pancake',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Lotus Pancake',
                'image' => 'images/items/lotus_pancake.jpg',
                'description' => 'Lotus Pancake',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Nutella Pancake',
                'image' => 'images/items/nutella_pancake.jpg',
                'description' => 'Nutella Pancake',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Oreo Pancake',
                'image' => 'images/items/oreo_pancake.jpg',
                'description' => 'Oreo Pancake',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Pistachio Pancake',
                'image' => 'images/items/pistachio_pancake.jpg',
                'description' => 'Pistachio Pancake',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'Red Velvet Pancake',
                'image' => 'images/items/red_velvet_pancake.jpg',
                'description' => 'Red Velvet Pancake',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 9,
                'name' => 'White Pancake',
                'image' => 'images/items/white_pancake.jpg',
                'description' => 'White Pancake',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Profiterole Items (Category ID: 17)
            [
                'category_id' => 17,
                'name' => 'Pyramide 4 Mix',
                'image' => 'images/items/pyramide_4_mix.jpg',
                'description' => 'Pyramide 4 Mix',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 17,
                'name' => 'Pyramide 4 With Belgium',
                'image' => 'images/items/pyramide_4_with_belgium.jpg',
                'description' => 'Pyramide 4 With Belgium',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 17,
                'name' => 'Pyramide 7 With Belgium',
                'image' => 'images/items/pyramide_7_with_belgium.jpg',
                'description' => 'Pyramide 7 With Belgium',
                'price' => 800000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 17,
                'name' => 'Pyramide 9 With Belgium',
                'image' => 'images/items/pyramide_9_with_belgium.jpg',
                'description' => 'Pyramide 9 With Belgium',
                'price' => 1000000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Small Pancake Items (Category ID: 10)
            [
                'category_id' => 10,
                'name' => 'Belgium Small Pancake',
                'image' => 'images/items/belgium_small_pancake.jpg',
                'description' => 'Belgium Small Pancake',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Box 24 Small Pancakes with Fruits and Chocolate',
                'image' => 'images/items/box_24_small_pancakes_with_fruits_and_chocolate.jpg',
                'description' => 'Box 24 Small Pancakes with Fruits and Chocolate',
                'price' => 600000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Box 24 Small Pancakes with Fruits and Pistachio',
                'image' => 'images/items/box_24_small_pancakes_with_fruits_and_pistachio.jpg',
                'description' => 'Box 24 Small Pancakes with Fruits and Pistachio',
                'price' => 700000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Dark 12 Small Pancake',
                'image' => 'images/items/dark_12_small_pancake.jpg',
                'description' => 'Dark 12 Small Pancake',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Galaxy 12 Small Pancake',
                'image' => 'images/items/galaxy_12_small_pancake.jpg',
                'description' => 'Galaxy 12 Small Pancake',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Italian Small Pancake',
                'image' => 'images/items/italian_small_pancake.jpg',
                'description' => 'Italian Small Pancake',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Kinder 12 Small Pancake',
                'image' => 'images/items/kinder_12_small_pancake.jpg',
                'description' => 'Kinder 12 Small Pancake',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Lotus 12 Small Pancake',
                'image' => 'images/items/lotus_12_small_pancake.jpg',
                'description' => 'Lotus 12 Small Pancake',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Nutella Small Pancake',
                'image' => 'images/items/nutella_small_pancake.jpg',
                'description' => 'Nutella Small Pancake',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Oreo Small Pancake',
                'image' => 'images/items/oreo_small_pancake.jpg',
                'description' => 'Oreo Small Pancake',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'Pistachio 12 Small Pancake',
                'image' => 'images/items/pistachio_12_small_pancake.jpg',
                'description' => 'Pistachio 12 Small Pancake',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 10,
                'name' => 'White 12 Small Pancake',
                'image' => 'images/items/white_12_small_pancake.jpg',
                'description' => 'White 12 Small Pancake',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Square Waffle Items (Category ID: 6)
            [
                'category_id' => 6,
                'name' => 'Belgium Square Waffle',
                'image' => 'images/items/belgium_square_waffle.jpg',
                'description' => 'Belgium Square Waffle',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Dark Square Waffle',
                'image' => 'images/items/dark_square_waffle.jpg',
                'description' => 'Dark Square Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Add Fruits Square Waffle',
                'image' => 'images/items/add_fruits_square_waffle.jpg',
                'description' => 'Add Fruits Square Waffle',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Galaxy Square Waffle',
                'image' => 'images/items/galaxy_square_waffle.jpg',
                'description' => 'Galaxy Square Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Ice Cream Ball',
                'image' => 'images/items/ice_cream_ball_square.jpg',
                'description' => 'Ice Cream Ball',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Italian Square Waffle',
                'image' => 'images/items/italian_square_waffle.jpg',
                'description' => 'Italian Square Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Kinder Square Waffle',
                'image' => 'images/items/kinder_square_waffle.jpg',
                'description' => 'Kinder Square Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Lotus Square Waffle',
                'image' => 'images/items/lotus_square_waffle.jpg',
                'description' => 'Lotus Square Waffle',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Nutella Square Waffle',
                'image' => 'images/items/nutella_square_waffle.jpg',
                'description' => 'Nutella Square Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Oreo Square Waffle',
                'image' => 'images/items/oreo_square_waffle.jpg',
                'description' => 'Oreo Square Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'Pistachio Square Waffle',
                'image' => 'images/items/pistachio_square_waffle.jpg',
                'description' => 'Pistachio Square Waffle',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 6,
                'name' => 'White Square Waffle',
                'image' => 'images/items/white_square_waffle.jpg',
                'description' => 'White Square Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Stick Waffle Items (Category ID: 7)
            [
                'category_id' => 7,
                'name' => 'Add Fruits',
                'image' => 'images/items/add_fruits_stick.jpg',
                'description' => 'Add Fruits',
                'price' => 200000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 7,
                'name' => 'Belgium Stick Waffle',
                'image' => 'images/items/belgium_stick_waffle.jpg',
                'description' => 'Belgium Stick Waffle',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 7,
                'name' => 'Dark Stick Waffle',
                'image' => 'images/items/dark_stick_waffle.jpg',
                'description' => 'Dark Stick Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 7,
                'name' => 'Galaxy Stick Waffle',
                'image' => 'images/items/galaxy_stick_waffle.jpg',
                'description' => 'Galaxy Stick Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 7,
                'name' => 'Italian Stick Waffle',
                'image' => 'images/items/italian_stick_waffle.jpg',
                'description' => 'Italian Stick Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 7,
                'name' => 'Lotus Stick Waffle',
                'image' => 'images/items/lotus_stick_waffle.jpg',
                'description' => 'Lotus Stick Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 7,
                'name' => 'Nutella Stick Waffle',
                'image' => 'images/items/nutella_stick_waffle.jpg',
                'description' => 'Nutella Stick Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 7,
                'name' => 'Oreo Stick Waffle',
                'image' => 'images/items/oreo_stick_waffle.jpg',
                'description' => 'Oreo Stick Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 7,
                'name' => 'Pistachio Stick Waffle',
                'image' => 'images/items/pistachio_stick_waffle.jpg',
                'description' => 'Pistachio Stick Waffle',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 7,
                'name' => 'White Stick Waffle',
                'image' => 'images/items/white_stick_waffle.jpg',
                'description' => 'White Stick Waffle',
                'price' => 350000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // Water Items (Category ID: 19)
            [
                'category_id' => 19,
                'name' => 'Pampa',
                'image' => 'images/items/pampa.jpg',
                'description' => 'Pampa',
                'price' => 10000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 19,
                'name' => 'Sohat',
                'image' => 'images/items/sohat.jpg',
                'description' => 'Sohat',
                'price' => 30000,
                'is_sale' => false,
                'sale_price' => null,
            ],

            // قشطوطة Items (Category ID: 21)
            [
                'category_id' => 21,
                'name' => 'مع رز بحليب',
                'image' => 'images/items/مع_رز_بحليب.jpg',
                'description' => 'مع رز بحليب',
                'price' => 100000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة إيطالي مع مكسرات مشكل',
                'image' => 'images/items/قشطوطة_إيطالي_مع_مكسرات_مشكل.jpg',
                'description' => 'قشطوطة إيطالي مع مكسرات مشكل',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بلجيكي',
                'image' => 'images/items/قشطوطة_بلجيكي.jpg',
                'description' => 'قشطوطة بلجيكي',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بلجيكي وبستاشيو مع برش',
                'image' => 'images/items/قشطوطة_بلجيكي_وبستاشيو_مع_برش.jpg',
                'description' => 'قشطوطة بلجيكي وبستاشيو مع برش',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بلجيكي وبستاشيو مع حب',
                'image' => 'images/items/قشطوطة_بلجيكي_وبستاشيو_مع_حب.jpg',
                'description' => 'قشطوطة بلجيكي وبستاشيو مع حب',
                'price' => 650000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بلجيكي ولوتس',
                'image' => 'images/items/قشطوطة_بلجيكي_ولوتس.jpg',
                'description' => 'قشطوطة بلجيكي ولوتس',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بلجيكي وفواكه',
                'image' => 'images/items/قشطوطة_بلجيكي_وفواكه.jpg',
                'description' => 'قشطوطة بلجيكي وفواكه',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بلجيكي مكسرات مشكل برش',
                'image' => 'images/items/قشطوطة_بلجيكي_مكسرات_مشكل_برش.jpg',
                'description' => 'قشطوطة بلجيكي مكسرات مشكل برش',
                'price' => 600000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بلجيكي مكسرات مشكل حب',
                'image' => 'images/items/قشطوطة_بلجيكي_مكسرات_مشكل_حب.jpg',
                'description' => 'قشطوطة بلجيكي مكسرات مشكل حب',
                'price' => 650000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بستاشيو اكسترا حب',
                'image' => 'images/items/قشطوطة_بستاشيو_اكسترا_حب.jpg',
                'description' => 'قشطوطة بستاشيو اكسترا حب',
                'price' => 600000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بستاشيو مع صوص بأنواعه',
                'image' => 'images/items/قشطوطة_بستاشيو_مع_صوص_بأنواعه.jpg',
                'description' => 'قشطوطة بستاشيو مع صوص بأنواعه',
                'price' => 450000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة سوبر (بلجيكي بستاشيو ولوتس)',
                'image' => 'images/items/قشطوطة_سوبر_بلجيكي_بستاشيو_ولوتس.jpg',
                'description' => 'قشطوطة سوبر (بلجيكي بستاشيو ولوتس)',
                'price' => 600000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة بستاشيو مع برش',
                'image' => 'images/items/قشطوطة_بستاشيو_مع_برش.jpg',
                'description' => 'قشطوطة بستاشيو مع برش',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة صوص بأنواعه',
                'image' => 'images/items/قشطوطة_صوص_بأنواعه.jpg',
                'description' => 'قشطوطة صوص بأنواعه',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة فواكه',
                'image' => 'images/items/قشطوطة_فواكه.jpg',
                'description' => 'قشطوطة فواكه',
                'price' => 500000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة كراميل',
                'image' => 'images/items/قشطوطة_كراميل.jpg',
                'description' => 'قشطوطة كراميل',
                'price' => 400000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة منجا مع بلجيكي',
                'image' => 'images/items/قشطوطة_منجا_مع_بلجيكي.jpg',
                'description' => 'قشطوطة منجا مع بلجيكي',
                'price' => 600000,
                'is_sale' => false,
                'sale_price' => null,
            ],
            [
                'category_id' => 21,
                'name' => 'قشطوطة نص بلجيكي نص فواكه',
                'image' => 'images/items/قشطوطة_نص_بلجيكي_نص_فواكه.jpg',
                'description' => 'قشطوطة نص بلجيكي نص فواكه',
                'price' => 550000,
                'is_sale' => false,
                'sale_price' => null,
            ],
        ];

        DB::table('items')->insert($items);
    }
}